declare module '@kangc/v-md-editor/lib/theme/vuepress.js'
declare module '@kangc/v-md-editor/lib/theme/github.js'
declare module '@kangc/v-md-editor'
declare module 'prismjs'
declare module '@kangc/v-md-editor/lib/lang/en-US'
declare module '@kangc/v-md-editor/lib/lang/zh-CN'
